# Shared venv-setup/dependency-install logic for run-backend.ps1,
# run-worker.ps1 and run-beat.ps1 - dot-sourced by each, e.g.:
#   . "$PSScriptRoot\dev-env.ps1"
#   Ensure-Environment
#
# All three scripts point at the same .venv and are meant to be started
# side-by-side (that's the whole point of splitting backend/worker/beat).
# Each used to independently run `pip install -r requirements.txt` with no
# coordination - two concurrent pip processes writing into the same
# site-packages directory race on any package upgrade, and a package with
# compiled DLLs (e.g. cryptography, which asyncssh requires an upgraded
# version of) is especially prone to failing with a confusing mid-install
# OSError rather than any kind of "wait your turn" message. A named,
# session-wide Mutex now serializes the actual `pip install` call across
# whichever of these three scripts gets there first; a requirements.txt
# hash stamp then lets the others skip installing entirely once it's done,
# so steady-state startup (nothing changed) never even touches the lock.

function Assert-LastExitCode([string]$step) {
    if ($LASTEXITCODE -ne 0) {
        throw "$step failed (exit code $LASTEXITCODE) - see the output above for the actual error."
    }
}

function Assert-RedisReachable {
    # Real (non-eager) mode needs Redis so the backend can hand jobs to the
    # worker. Fails fast with an explanation instead of letting uvicorn
    # start and every job then error out with a connection refused.
    $redisHost = "localhost"
    $redisPort = 6379
    if ($env:REDIS_URL) {
        try {
            $uri = [Uri]$env:REDIS_URL
            if ($uri.Host) { $redisHost = $uri.Host }
            if ($uri.Port -gt 0) { $redisPort = $uri.Port }
        } catch {
            # Fall back to the localhost:6379 default if REDIS_URL doesn't parse.
        }
    }

    $probe = New-Object System.Net.Sockets.TcpClient
    $connected = $false
    try {
        $result = $probe.BeginConnect($redisHost, $redisPort, $null, $null)
        $connected = $result.AsyncWaitHandle.WaitOne(1500) -and $probe.Connected
    } catch {
        $connected = $false
    } finally {
        $probe.Close()
    }

    if (-not $connected) {
        throw @"
Can't reach Redis at ${redisHost}:${redisPort}.

Real (non-eager) mode needs Redis running so the backend can hand jobs off
to a Celery worker instead of blocking the HTTP request until every device
finishes. On Windows without Docker, the easiest way to get this is Memurai
(https://www.memurai.com/) - a free, native Windows Redis-compatible service.
Install it, make sure the service is running, then start this script again.

Or, if you just want the quick-testing behavior (no Redis/worker needed,
but "Start collection" blocks until all devices finish), add -Eager.
"@
    }
    Write-Host "Redis reachable at ${redisHost}:${redisPort}."
}

function Ensure-EnvFile {
    # A fresh clone has no backend\.env, so the app would run on the
    # placeholder secrets from config.py (fine for development, and the app
    # says so at startup - but a real key per install costs nothing). Writes
    # one with random JWT_SECRET_KEY / CREDENTIAL_ENCRYPTION_KEY the first
    # time. Existing files are never touched.
    $envPath = "$PSScriptRoot\.env"
    if (Test-Path $envPath) { return }
    Write-Host "Creating backend\.env with freshly generated secrets..."
    $jwt = python -c "import secrets; print(secrets.token_urlsafe(48))"
    $fernet = python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
    if ($LASTEXITCODE -ne 0 -or -not $fernet) {
        Write-Host "Could not generate secrets (is the venv active?). Continuing with the built-in development defaults."
        return
    }
    @"
# Generated by dev-env.ps1 on $(Get-Date -Format s). Keep this file with your database backups:
# CREDENTIAL_ENCRYPTION_KEY protects every stored device password.
ENVIRONMENT=development
JWT_SECRET_KEY=$jwt
CREDENTIAL_ENCRYPTION_KEY=$fernet
"@ | Out-File -Encoding ascii $envPath
}

function Ensure-Environment {
    if (-not (Test-Path "$PSScriptRoot\.venv")) {
        Write-Host "Creating virtual environment..."
        python -m venv "$PSScriptRoot\.venv"
        Assert-LastExitCode "Virtual environment creation"
    }

    $activate = "$PSScriptRoot\.venv\Scripts\Activate.ps1"
    if (-not (Test-Path $activate)) {
        throw "Could not find $activate - venv creation may have failed."
    }
    & $activate

    $reqPath = "$PSScriptRoot\requirements.txt"
    $reqHash = (Get-FileHash $reqPath -Algorithm SHA256).Hash
    $stampPath = "$PSScriptRoot\.venv\install-stamp.txt"

    if ((Test-Path $stampPath) -and ((Get-Content $stampPath -Raw).Trim() -eq $reqHash)) {
        Write-Host "Dependencies already up to date."
        Ensure-EnvFile
        return
    }

    # Only one of run-backend/run-worker/run-beat should actually run pip
    # install at a time - the rest wait here, then re-check the stamp
    # below (whoever held the lock before them may have just finished
    # installing this exact requirements.txt, in which case they skip too).
    $mutex = New-Object System.Threading.Mutex($false, "ConfigCollectorPipInstall")
    Write-Host "Waiting for dependency install lock (another run-*.ps1 script may be installing)..."
    [void]$mutex.WaitOne()
    try {
        if ((Test-Path $stampPath) -and ((Get-Content $stampPath -Raw).Trim() -eq $reqHash)) {
            Write-Host "Dependencies already up to date (installed by another script while we waited)."
            return
        }

        Write-Host "Installing/updating dependencies..."
        pip install -r $reqPath
        Assert-LastExitCode "pip install"
        Set-Content -Path $stampPath -Value $reqHash
    } finally {
        $mutex.ReleaseMutex()
    }
    Ensure-EnvFile
}
