"""baseline

Revision ID: 7be3e846af07
Revises: 
Create Date: 2026-09-16 07:58:41.730225
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app.models.base


# revision identifiers, used by Alembic.
revision: str = '7be3e846af07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('snapshot_retention_days', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_profiles',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('commands', sa.Text(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'device_type', name='uq_command_profiles_org_device_type')
    )
    op.create_table('credentials',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.String(length=512), nullable=False),
    sa.Column('encrypted_enable_secret', sa.String(length=512), nullable=True),
    sa.Column('mfa_mode', sa.Enum('NONE', 'PUSH', 'PASSCODE', name='mfamode'), nullable=False),
    sa.Column('otp_delimiter', sa.String(length=8), nullable=False),
    sa.Column('auth_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('fallback_credential_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fallback_credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_org_id'), ['org_id'], unique=False)

    op.create_table('custom_device_types',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('netmiko_driver', sa.String(length=64), nullable=False),
    sa.Column('default_commands', sa.Text(), nullable=False),
    sa.Column('secret_supported', sa.Boolean(), nullable=False),
    sa.Column('timing_read', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_custom_device_types_org_key')
    )
    with op.batch_alter_table('custom_device_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_device_types_org_id'), ['org_id'], unique=False)

    op.create_table('hostname_rules',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('match_mode', sa.String(length=16), nullable=False),
    sa.Column('device_role', sa.String(length=64), nullable=True),
    sa.Column('role_label', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hostname_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hostname_rules_org_id'), ['org_id'], unique=False)

    op.create_table('ping_monitor_configs',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('alert_on_down', sa.Boolean(), nullable=False),
    sa.Column('alert_on_up', sa.Boolean(), nullable=False),
    sa.Column('history_days', sa.Integer(), nullable=False),
    sa.Column('last_run_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('snmp_profiles',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Enum('V2C', 'V3', name='snmpversion'), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('encrypted_community', sa.String(length=512), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('security_level', sa.Enum('NO_AUTH_NO_PRIV', 'AUTH_NO_PRIV', 'AUTH_PRIV', name='snmpsecuritylevel'), nullable=True),
    sa.Column('auth_protocol', sa.Enum('MD5', 'SHA', 'SHA224', 'SHA256', 'SHA384', 'SHA512', name='snmpauthprotocol'), nullable=True),
    sa.Column('encrypted_auth_password', sa.String(length=512), nullable=True),
    sa.Column('priv_protocol', sa.Enum('DES', 'TRIPLE_DES', 'AES128', 'AES192', 'AES256', name='snmpprivprotocol'), nullable=True),
    sa.Column('encrypted_priv_password', sa.String(length=512), nullable=True),
    sa.Column('context_name', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snmp_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snmp_profiles_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('collection_jobs',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_by_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHENTICATING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_jobs_org_id'), ['org_id'], unique=False)

    op.create_table('devices',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('credential_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('snmp_profile_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('custom_commands', sa.String(length=1024), nullable=True),
    sa.Column('device_role', sa.String(length=64), nullable=True),
    sa.Column('console_host', sa.String(length=255), nullable=True),
    sa.Column('console_port', sa.Integer(), nullable=True),
    sa.Column('console_protocol', sa.String(length=8), nullable=True),
    sa.Column('console_credential_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('console_connect_command', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['console_credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['snmp_profile_id'], ['snmp_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_org_id'), ['org_id'], unique=False)

    op.create_table('dns_check_jobs',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_by_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHENTICATING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dns_check_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dns_check_jobs_org_id'), ['org_id'], unique=False)

    op.create_table('firmware_images',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('uploaded_by_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firmware_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firmware_images_org_id'), ['org_id'], unique=False)

    op.create_table('snmp_jobs',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_by_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('snmp_profile_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('extra_oids', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'AUTHENTICATING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['snmp_profile_id'], ['snmp_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snmp_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snmp_jobs_org_id'), ['org_id'], unique=False)

    op.create_table('snmp_monitor_configs',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('device_ids', sa.Text(), nullable=True),
    sa.Column('snmp_profile_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('alert_link_down', sa.Boolean(), nullable=False),
    sa.Column('alert_link_up', sa.Boolean(), nullable=False),
    sa.Column('alert_ap_down', sa.Boolean(), nullable=False),
    sa.Column('alert_ap_up', sa.Boolean(), nullable=False),
    sa.Column('alert_device_down', sa.Boolean(), nullable=False),
    sa.Column('alert_device_up', sa.Boolean(), nullable=False),
    sa.Column('alert_syslog_max_level', sa.Integer(), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('encrypted_smtp_password', sa.String(length=512), nullable=True),
    sa.Column('smtp_starttls', sa.Boolean(), nullable=False),
    sa.Column('smtp_ssl', sa.Boolean(), nullable=False),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('next_run_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['snmp_profile_id'], ['snmp_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('collection_job_items',
    sa.Column('job_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('device_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'AUTHENTICATING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('used_fallback_credential', sa.Boolean(), nullable=False),
    sa.Column('live_output', sa.Text(), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['collection_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_job_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_job_items_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_job_items_job_id'), ['job_id'], unique=False)

    op.create_table('dns_check_job_items',
    sa.Column('job_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHENTICATING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('ping_ok', sa.Boolean(), nullable=True),
    sa.Column('forward_ok', sa.Boolean(), nullable=True),
    sa.Column('forward_ips', sa.Text(), nullable=True),
    sa.Column('reverse_ok', sa.Boolean(), nullable=True),
    sa.Column('reverse_hostname', sa.String(length=255), nullable=True),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['dns_check_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dns_check_job_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dns_check_job_items_job_id'), ['job_id'], unique=False)

    op.create_table('firmware_upgrade_jobs',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_by_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('firmware_image_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('protocol', sa.Enum('TFTP', 'FTP', 'SCP', name='transferprotocol'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHENTICATING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firmware_image_id'], ['firmware_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firmware_upgrade_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firmware_upgrade_jobs_org_id'), ['org_id'], unique=False)

    op.create_table('ping_samples',
    sa.Column('device_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('checked_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('rtt_ms', sa.Float(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ping_samples', schema=None) as batch_op:
        batch_op.create_index('ix_ping_samples_device_time', ['device_id', 'checked_at'], unique=False)

    op.create_table('ping_statuses',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('device_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_change_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_rtt_ms', sa.Float(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    with op.batch_alter_table('ping_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ping_statuses_org_id'), ['org_id'], unique=False)

    op.create_table('schedules',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_by_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('device_ids', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Enum('ONCE', 'EVERY_N_HOURS', 'DAILY', 'WEEKLY', 'MONTHLY', name='schedulefrequency'), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('run_at_hour', sa.Integer(), nullable=True),
    sa.Column('run_at_minute', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('run_once_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('next_run_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_job_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_job_id'], ['collection_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_org_id'), ['org_id'], unique=False)

    op.create_table('snmp_alerts',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('device_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('LINK_DOWN', 'LINK_UP', 'AP_DOWN', 'AP_UP', 'DEVICE_DOWN', 'DEVICE_UP', 'SYSLOG', 'PING_DOWN', 'PING_UP', name='snmpalertkind'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('emailed', sa.Boolean(), nullable=False),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snmp_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snmp_alerts_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snmp_alerts_org_id'), ['org_id'], unique=False)

    op.create_table('snmp_job_items',
    sa.Column('job_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('device_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('profile_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'AUTHENTICATING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('live_output', sa.Text(), nullable=False),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['snmp_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snmp_job_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snmp_job_items_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snmp_job_items_job_id'), ['job_id'], unique=False)

    op.create_table('snmp_monitor_states',
    sa.Column('org_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('device_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'device_id', name='uq_snmp_monitor_states_device')
    )
    with op.batch_alter_table('snmp_monitor_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snmp_monitor_states_org_id'), ['org_id'], unique=False)

    op.create_table('config_snapshots',
    sa.Column('device_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('job_item_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('collected_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_item_id'], ['collection_job_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_snapshots_device_id'), ['device_id'], unique=False)

    op.create_table('firmware_upgrade_job_items',
    sa.Column('job_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('device_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'AUTHENTICATING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('live_output', sa.Text(), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['firmware_upgrade_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firmware_upgrade_job_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firmware_upgrade_job_items_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firmware_upgrade_job_items_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware_upgrade_job_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firmware_upgrade_job_items_job_id'))
        batch_op.drop_index(batch_op.f('ix_firmware_upgrade_job_items_device_id'))

    op.drop_table('firmware_upgrade_job_items')
    with op.batch_alter_table('config_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_snapshots_device_id'))

    op.drop_table('config_snapshots')
    with op.batch_alter_table('snmp_monitor_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snmp_monitor_states_org_id'))

    op.drop_table('snmp_monitor_states')
    with op.batch_alter_table('snmp_job_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snmp_job_items_job_id'))
        batch_op.drop_index(batch_op.f('ix_snmp_job_items_device_id'))

    op.drop_table('snmp_job_items')
    with op.batch_alter_table('snmp_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snmp_alerts_org_id'))
        batch_op.drop_index(batch_op.f('ix_snmp_alerts_device_id'))

    op.drop_table('snmp_alerts')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_org_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('ping_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ping_statuses_org_id'))

    op.drop_table('ping_statuses')
    with op.batch_alter_table('ping_samples', schema=None) as batch_op:
        batch_op.drop_index('ix_ping_samples_device_time')

    op.drop_table('ping_samples')
    with op.batch_alter_table('firmware_upgrade_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firmware_upgrade_jobs_org_id'))

    op.drop_table('firmware_upgrade_jobs')
    with op.batch_alter_table('dns_check_job_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dns_check_job_items_job_id'))

    op.drop_table('dns_check_job_items')
    with op.batch_alter_table('collection_job_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_job_items_job_id'))
        batch_op.drop_index(batch_op.f('ix_collection_job_items_device_id'))

    op.drop_table('collection_job_items')
    op.drop_table('snmp_monitor_configs')
    with op.batch_alter_table('snmp_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snmp_jobs_org_id'))

    op.drop_table('snmp_jobs')
    with op.batch_alter_table('firmware_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firmware_images_org_id'))

    op.drop_table('firmware_images')
    with op.batch_alter_table('dns_check_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dns_check_jobs_org_id'))

    op.drop_table('dns_check_jobs')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_org_id'))

    op.drop_table('devices')
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_jobs_org_id'))

    op.drop_table('collection_jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('snmp_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snmp_profiles_org_id'))

    op.drop_table('snmp_profiles')
    op.drop_table('ping_monitor_configs')
    with op.batch_alter_table('hostname_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostname_rules_org_id'))

    op.drop_table('hostname_rules')
    with op.batch_alter_table('custom_device_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_device_types_org_id'))

    op.drop_table('custom_device_types')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_org_id'))

    op.drop_table('credentials')
    op.drop_table('command_profiles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
